# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d8f0b01674fc38beb40519b585a0d1bcdcba45fe5e9f103c12120b0d89e4b75a155bec5afe39e131de9879dbc7e891e0521c44f0593b7e6d0044ebc2f0bf0ce

test:
  secret_key_base: e7d3ed721d57a89d65f8cc025c6c0349b639123b170e7ab4e1dec5ce266e313b7d889f8465dd5126498d97a7e27bbb6654099f6ce344e4f2d46f6381de5e6c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
